config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :posts, except: :new do
    resources :comments, only: [:new]
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :comments, except: [:new] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  root to: 'subs#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :author, :post_id, presence: true

  belongs_to :post, inverse_of: :comments
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :comments
  )

  has_many(
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_id,
    primary_key: :id,
    inverse_of: :parent_comment,
    dependent: :destroy
  )

  belongs_to(
    :parent_comment,
    class_name: "Comment",
    foreign_key: :parent_id,
    primary_key: :id,
    inverse_of: :child_comments
  )
  
  has_many :votes, as: :votable

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @post_id = params[:post_id]
    render :new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.score = 0

    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:notice] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def edit
    @comment = Comment.find(params[:id])
    render :edit
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to post_url(@comment.post)
    else
      flash.now[:notice] = @comment.errors.full_messages
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to post_url(@comment.post)
  end
  
  def upvote
    @comment = Comment.find(params[:id])
    @comment.score += 1
    @comment.save
    
    redirect_to post_url(@comment.post)
  end
  
  def downvote
    @comment = Comment.find(params[:id])
    @comment.score -= 1
    @comment.save
    
    redirect_to post_url(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% if comment.persisted? %>
  <% target_url = comment_url(comment) %>
  <% target_verb = "PATCH" %>
<% else %>
  <% target_url = comments_url %>
  <% target_verb = "POST" %>
<% end %>

<form action="<%= target_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= target_verb %>" >
  <input type="hidden" name="comment[post_id]" value="<%= post_id %>">
  <%= auth_token %>

  <label for="comment_content">Comment:</label>
  <textarea id="comment_content"
            name="comment[content]"><%= comment.content %></textarea>

  <button>Submit</button>
</form>

app/views/comments/_reply.html.erb
<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" value="<%= comment.id %>" name="comment[parent_id]">
  <input type="hidden" value="<%= comment.post_id %>" name="comment[post_id]">

  <label for="comment_content">Reply:</label>
  <textarea id="comment_content"
            name="comment[content]"></textarea>

  <button>Submit</button>

</form>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form", comment: @comment, post_id: @comment.post_id %>

app/views/comments/new.html.erb
<h1>Create Comment</h1>

<%= render "form", comment: @comment, post_id: @post_id %>

app/views/comments/show.html.erb
<h1><%= @comment.author.email %>'s Comment</h1>

<pre><%= @comment.content %></pre>

<%= render "reply", comment: @comment %>