config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :posts, except: :new do
    resources :comments, only: [:new]
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :comments, except: [:new] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  root to: 'subs#index'
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :moderator_id, :title, presence: true
  validates :title, uniqueness: true

  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id,
    inverse_of: :subs
  )

  has_many :post_subs, inverse_of: :sub

  has_many :posts, through: :post_subs, source: :post, inverse_of: :subs

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_filter :ensure_ownership, only: [:edit, :update]

  def new
    @sub = Sub.new

    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:notice] = @sub.errors.full_messages

      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts

    render :show
  end

  def index
    @subs = Sub.all

    render :index
  end

  def edit
    @sub = Sub.find(params[:id])

    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:notice] = @sub.errors.full_messages
      render :edit
    end
  end

  def ensure_ownership
    @sub = Sub.find(params[:id])
    unless current_user == @sub.moderator
      flash[:notice] = ["Don't touch that."]
      redirect_to subs_url
    end
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% if sub.persisted? %>
  <% target_url = sub_url(sub) %>
  <% target_verb = "PATCH" %>
  <% button_text = "Save changes" %>
<% else%>
  <% target_url = subs_url %>
  <% target_verb = "POST" %>
  <% button_text = "Create sub" %>
<% end %>


<form action="<%= target_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= target_verb %>">
  <%= auth_token %>

  <label for="sub_title">Title</label>
  <input type="text"
         id="sub_title"
         name="sub[title]"
         value="<%= sub.title %>">

  <br>

  <label for="sub_description">Description</label>
  <textarea id="sub_description"
            name="sub[description]"><%= sub.description %>
  </textarea>

  <button><%= button_text %></button>
</form>

app/views/subs/_vote.html.erb
<% if direction == :up %>
  <% target_url = upvote_post_url(post) %>
<% else %>
  <% target_url = downvote_post_url(post) %>
<% end %>

<form action="<%= target_url %>", method="POST">
	
	<%= auth_token %>
	
	<input type="hidden", name="sub[post_id]">
	
	<button><%= direction %>vote</button>
</form>

app/views/subs/edit.html.erb
<h1>Edit <%= @sub.title %></h1>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>Subs</h1>

<ul>
<% @subs.each do |sub| %>
  <li>
  <a href="<%= sub_url(sub) %>"><%= sub.title %><br><br>
  </a>
  </li>
<% end %>
</ul>

<a href="<%= new_sub_url %>">Create a sub</a>

app/views/subs/new.html.erb
<h1>Create a sub!</h1>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<%= @sub.description %>
<br><br>

<ol>
  <% @sub.posts.each do |post| %>
    <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
	Score:  <%= post.score %>
	<%= render "vote", direction: :up, post: post %>
	<%= render "vote", direction: :down, post: post %>
	
    <br><br>
  <% end %>
</ol>

<% if current_user %>
  <br><br>
  <a href="<%= new_sub_post_url(@sub) %>">New Post</a>
  <br><br>
<% end %>

<% if current_user == @sub.moderator %>
  <a href="<%= edit_sub_url(@sub) %>">Edit sub</a>
  <br><br>
<% end %>

<a href="<%= subs_url %>">Back to all subs</a>