config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :subs do
    resources :posts, only: [:new]
  end

  resources :posts, except: :new do
    resources :comments, only: [:new]
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  resources :comments, except: [:new] do
    member do
      post 'upvote'
      post 'downvote'
    end
  end

  root to: 'subs#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id,
    inverse_of: :posts,
  )

  has_many :post_subs, inverse_of: :post

  has_many :subs, through: :post_subs, source: :sub, inverse_of: :posts

  has_many :comments, inverse_of: :post

  has_many(
    :top_level_comments,
    -> { where(parent_id: nil) },
    class_name: "Comment",
    foreign_key: :post_id,
    primary_key: :id
  )
  
  has_many :votes, as: :votable
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @subs = Sub.all
    @source_sub_id = params[:sub_id]

    render :new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.score = 0

    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:notices] = @post.errors.full_messages
      @subs = Sub.all
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all

    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)

      redirect_to post_url(@post)
    else
      flash.now[:notice] = @post.errors.full_messages

      render :edit
    end
  end
  
  def upvote
    @post = Post.find(params[:id])
    @post.score += 1
    @post.save
    
    redirect_to sub_url(@post.subs.first)
  end
  
  def downvote
    @post = Post.find(params[:id])
    @post.score -= 1
    @post.save
    
    redirect_to sub_url(@post.subs.first)
  end

  # def destroy
  #   @post = Post.find(params[:id])
  #   @post.destroy
  #
  #   redirect_to subs_url
  # end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  
  def show_children(comment)
    comment.child_comments.each do |child|
      <<-HTML.html_safe
        <ul>
          <li>
            <pre>#{ child.content }</pre>
            <a href="#{comment_url(child)}">Go to Comment</a>
            <h6>Posted by '#{child.author.email}'
              at <%= child.created_at %></h6>
          </li>
        <ul>
      HTML
    end
  end
  
end

app/views/posts/_form.html.erb
<% if post.persisted? %>
  <% target_url = post_url(post) %>
  <% target_verb = "PATCH" %>
  <% button_text = "Save Changes" %>
<% else %>
  <% target_url = posts_url %>
  <% target_verb = "POST" %>
  <% button_text = "Create Post" %>
<% end %>

<form action="<%= target_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= target_verb %>">

  <%= auth_token %>

  <p>
    <label for="post_title">Title</label>
    <input type="text"
           id="post_title"
           name="post[title]"
           value="<%= post.title %>">
  </p>

  <p>
    <% subs.each do |sub| %>
      <label for="post_sub_ids"><%= sub.title %></label>
      <input type="hidden" id="post_sub_ids" name="post[sub_ids][]" value="">
      <input type="checkbox"
             id="post_sub_ids"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <% if source_sub_id.to_i == sub.id.to_i ||
                   post.sub_ids.include?(sub.id) %>
             checked
             <% end %>>
   <% end %>
  </p>

  <p>
    <label for="post_url">Link URL (optional)</label>
    <input type="text"
           id="post_url"
           name="post[url]"
           value="<%= post.url %>">
  </p>
  <p>
    <label for="post_content">Content (optional)</label>
    <textarea id="post_content"
              name="post[content]"><%= post.content %></textarea>
  </p>

  <button><%= button_text %></button>
</form>

app/views/posts/_vote.html.erb
<% if direction == :up %>
  <% target_url = upvote_comment_url(comment) %>
<% else %>
  <% target_url = downvote_comment_url(comment) %>
<% end %>

<form action="<%= target_url %>", method="POST">
	
	<%= auth_token %>
	
	<input type="hidden", name="post[comment_id]">
	
	<button><%= direction %>vote</button>
</form>

app/views/posts/edit.html.erb
<h1>Edit <%= @post.title %></h1>

<%= render "form", post: @post, subs: @subs, source_sub_id: @source_sub_id %>

app/views/posts/new.html.erb
<h1>Make a Post</h1>

<%= render "form", post: @post, subs: @subs, source_sub_id: @source_sub_id %>

app/views/posts/show.html.erb
<% if @post.url.present? %>
  <% post_title = (link_to "#{@post.title}", "#{@post.url}")%>
<% else %>
  <% post_title = @post.title %>
<% end %>


<h1><%= post_title %> (<%= @post.score %>)</h1>
<div>
  <%= @post.content %>
</div>

<h3>Comments (<%= @post.comments.length %>)</h3>
<ul>
  <% @post.comments.each do |comment| %>
    <% if comment.parent_comment.nil? %>
	  <li>
        <pre><%= comment.content %> (<%= comment.score %>)</pre>
        <a href="<%= comment_url(comment) %>">Go to Comment</a>
        <h6>Posted by '<%= comment.author.email %>'
          at <%= comment.created_at %></h6>
		  
  	  	<%= render "vote", direction: :up, comment: comment %>
  	  	<%= render "vote", direction: :down, comment: comment %>

        <% if comment.author == current_user %>

          <a href="<%= edit_comment_url(comment) %>">
            Edit (because you should be embarassed by that)</a>

          <%= button_to "Delete", comment_url(comment), method: :delete %>

        <% end %>
		<ul>
	  <% comment.child_comments.each do |child| %>
          <li>
            <pre> <%= child.content %> </pre>
            <a href="<%= comment_url(child) %>">Go to Comment</a>
			<%= button_to "Delete Comment", comment_url(child), method: :delete %>
            <h6>Posted by '<%= child.author.email %>'
              at <%= child.created_at %></h6>
			  
	    	  	<%= render "vote", direction: :up, comment: comment %>
	    	  	<%= render "vote", direction: :down, comment: comment %>
			  
          </li>
	  <% end %>
	
	<% end %>
	
  <% end %>
</ul>

<% if current_user %>
  <br>
  <a href="<%= new_post_comment_url(@post) %>">Comment on this Post</a>
<% end %>

<% if @post.author == current_user %>
  <br>
  <a href="<%= edit_post_url(@post) %>">Edit Post</a>
<% end %>

<br><br>
Posted in:
<% @post.subs.each do |sub| %>
  <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
<% end %>